fix: Schema is not retaining the correct column order
wintersrd/pipelinewise-tap-mssql pull request #73
Opened 2024-07-17 02:08 UTC by mjsqu

Fixes #62 

Also includes modifications to the existing `TestSelectsAppropriateColumns`:

* Adds more columns
* Assertion changed to compare two lists, will fail if they are not in the same order
* Added a duplicate column to the select list

Adds new test `TestInvalidInclusion` which tests that an exception is raised when an `inclusion` value of "invalid" is supplied, which is not one of the valid values:
* automatic
* available
* unsupported

2024-07-17 21:30 UTC, mjsqu commented
For my own future reference, I could have more quickly run my updated tests by doing:

```
poetry install
poetry run pytest tests/test_tap_mssql.py -k TestSelects -v
poetry run pytest tests/test_tap_mssql.py -k TestInvalid -v
```

Running all tests requires the build of a database (as supplied by the docker image in the `tox.ini`) - but the functionality I was testing didn't require a connection to SQL Server.

2024-07-22 04:17 UTC, s7clarke10 requested changes
Hi @mjsqu ,

I have reviewed the changes and like what you have done - thank you 🥇 .

My testing included.

1. Peer Review of the code
2. Compare the discovery of the schema (current vs PR)
3. Compare the column ordering of loaded data in target-snowflake (current vs PR)
4. Compare the content diff of result in target-snowflake (current vs PR).

All passed successfully.

Could we add the following changes however.

1. Update the .bumpversion.cfg with new version
2. Update the pyproject.toml with new version
3. Update the CHANGELOG.md with description of latest version / change.
4. Rebuild the pyproject lockfile 👍 
```shell
   poetry lock --no-update```


Thank you.

2024-07-22 04:49 UTC, mjsqu commented
These are done:

- Update the .bumpversion.cfg with new version
- Update the pyproject.toml with new version
- Update the CHANGELOG.md with description of latest version / change.

I ran `poetry lock --no-update` but there are no changes as I have made no updates to dependencies

2024-07-22 20:37 UTC, s7clarke10 approved these changes

2024-07-22 20:38 UTC, s7clarke10 commented
Thank you for adding the version updates. Change approved. Thank you.

2024-07-22 21:04 UTC, merged